
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Dec 20 2024 13:08:17 IST (Dec 20 2024 07:38:17 UTC)

// Verification Directory fv/elevator 

module elevator(Request_Floor, In_Current_Floor, Over_Weight,
     Door_Open, Floor_Sensor, clk, reset, Out_Current_Floor, Direction,
     Complete, Door_Alert, Weight_Alert);
  input [3:0] Request_Floor, In_Current_Floor;
  input Over_Weight, Door_Open, Floor_Sensor, clk, reset;
  output [3:0] Out_Current_Floor;
  output Direction, Complete, Door_Alert, Weight_Alert;
  wire [3:0] Request_Floor, In_Current_Floor;
  wire Over_Weight, Door_Open, Floor_Sensor, clk, reset;
  wire [3:0] Out_Current_Floor;
  wire Direction, Complete, Door_Alert, Weight_Alert;
  wire [7:0] door_timer;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2, n_0, n_1,
       n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_36, n_37, n_38, n_39, n_40, n_41, n_42, n_43;
  wire n_44, n_45, n_46, n_47, n_48, n_49, n_50, n_51;
  wire n_52, n_53, n_54, n_55, n_56, n_57, n_58, n_59;
  wire n_60, n_61, n_62, n_63, n_64, n_65, n_66, n_67;
  wire n_68, n_69, n_70, n_71, n_72, n_73, n_74;
  dfcrq1 \door_timer_reg[1] (.CDN (n_74), .CP (clk), .D (n_69), .Q
       (door_timer[1]));
  dfcrq1 \door_timer_reg[2] (.CDN (n_74), .CP (clk), .D (n_73), .Q
       (door_timer[2]));
  dfcrq1 \door_timer_reg[3] (.CDN (n_74), .CP (clk), .D (n_68), .Q
       (door_timer[3]));
  dfcrq1 \door_timer_reg[4] (.CDN (n_74), .CP (clk), .D (n_70), .Q
       (door_timer[4]));
  dfcrq1 \door_timer_reg[5] (.CDN (n_74), .CP (clk), .D (n_72), .Q
       (door_timer[5]));
  dfcrq1 \door_timer_reg[6] (.CDN (n_74), .CP (clk), .D (n_66), .Q
       (door_timer[6]));
  dfcrq1 \door_timer_reg[0] (.CDN (n_74), .CP (clk), .D (n_67), .Q
       (door_timer[0]));
  dfcrq1 \door_timer_reg[7] (.CDN (n_74), .CP (clk), .D (n_65), .Q
       (door_timer[7]));
  oaim21d1 g2396__2398(.A (n_71), .B1 (Door_Open), .B2 (n_34), .ZN
       (n_73));
  oaim21d1 g2398__5107(.A (n_71), .B1 (n_60), .B2 (Door_Open), .ZN
       (n_72));
  oaim21d1 g2399__6260(.A (n_71), .B1 (n_48), .B2 (Door_Open), .ZN
       (n_70));
  oaim21d1 g2394__4319(.A (n_71), .B1 (Door_Open), .B2 (n_21), .ZN
       (n_69));
  oaim21d1 g2400__8428(.A (n_71), .B1 (n_39), .B2 (Door_Open), .ZN
       (n_68));
  oai21d1 g2395__5526(.A (n_71), .B1 (n_64), .B2 (door_timer[0]), .ZN
       (n_67));
  oaim21d1 g2401__6783(.A (n_71), .B1 (n_62), .B2 (Door_Open), .ZN
       (n_66));
  aoim21d1 g2402__3680(.A (n_64), .B1 (n_63), .B2 (door_timer[7]), .ZN
       (n_65));
  nd03d1 g2403__1617(.A1 (n_63), .A2 (Door_Open), .A3 (door_timer[7]),
       .ZN (n_71));
  dfbrb1 \Out_Current_Floor_reg[2] (.CDN (n_4), .SDN (n_6), .CP (clk),
       .D (n_61), .Q (Out_Current_Floor[2]), .QN (UNCONNECTED));
  ah01d1 g2404__2802(.A (n_59), .B (door_timer[6]), .CO (n_63), .S
       (n_62));
  aor221d1 g2406__1705(.A (n_57), .B1 (n_52), .B2
       (Out_Current_Floor[2]), .C1 (n_56), .C2 (n_9), .Z (n_61));
  dfbrb1 \Out_Current_Floor_reg[3] (.CDN (n_5), .SDN (n_2), .CP (clk),
       .D (n_58), .Q (Out_Current_Floor[3]), .QN (UNCONNECTED0));
  dfbrb1 \Out_Current_Floor_reg[1] (.CDN (n_7), .SDN (n_1), .CP (clk),
       .D (n_55), .Q (Out_Current_Floor[1]), .QN (UNCONNECTED1));
  dfbrb1 \Out_Current_Floor_reg[0] (.CDN (n_0), .SDN (n_3), .CP (clk),
       .D (n_54), .Q (Out_Current_Floor[0]), .QN (UNCONNECTED2));
  ah01d1 g2408__5122(.A (n_47), .B (door_timer[5]), .CO (n_59), .S
       (n_60));
  oaim22d1 g2413__8246(.A1 (n_57), .A2 (n_10), .B1 (n_56), .B2
       (Out_Current_Floor[2]), .ZN (n_58));
  oai222d1 g2410__7098(.A1 (n_51), .A2 (n_49), .B1 (n_53), .B2 (n_12),
       .C1 (n_50), .C2 (n_23), .ZN (n_55));
  mx02d1 g2414__6131(.I0 (Out_Current_Floor[0]), .I1 (n_17), .S (n_53),
       .Z (n_54));
  oai211d1 g2412__1881(.A (n_53), .B (n_51), .C1 (n_50), .C2 (n_49),
       .ZN (n_52));
  nr03d1 g2420__5115(.A1 (Out_Current_Floor[2]), .A2 (n_22), .A3
       (n_50), .ZN (n_57));
  dfcrq1 Direction_reg(.CDN (n_74), .CP (clk), .D (n_45), .Q
       (Direction));
  ah01d1 g2415__7482(.A (n_38), .B (door_timer[4]), .CO (n_47), .S
       (n_48));
  nd02d1 g2417__4733(.A1 (n_46), .A2 (n_50), .ZN (n_53));
  dfcrq1 Complete_reg(.CDN (n_74), .CP (clk), .D (n_42), .Q (Complete));
  nd12d1 g2418__6161(.A1 (n_46), .A2 (n_44), .ZN (n_51));
  oaim21d1 g2422__9315(.A (n_41), .B1 (n_43), .B2 (Direction), .ZN
       (n_45));
  nr02d1 g2419__9945(.A1 (n_44), .A2 (n_46), .ZN (n_56));
  nd12d1 g2423__2883(.A1 (n_43), .A2 (Floor_Sensor), .ZN (n_50));
  inv0d0 g2430(.I (n_40), .ZN (n_42));
  nd12d1 g2421__2346(.A1 (n_41), .A2 (Floor_Sensor), .ZN (n_46));
  oai21d1 g2431__1666(.A (n_37), .B1 (n_35), .B2 (Over_Weight), .ZN
       (n_40));
  ah01d1 g2425__7410(.A (n_33), .B (door_timer[3]), .CO (n_38), .S
       (n_39));
  nd12d1 g2427__6417(.A1 (n_36), .A2 (n_37), .ZN (n_43));
  oai211d1 g2424__5477(.A (n_27), .B (n_37), .C1 (n_32), .C2 (n_16),
       .ZN (n_41));
  decrq1 Door_Alert_reg(.CDN (n_74), .CP (clk), .D (Door_Open), .ENN
       (n_30), .Q (Door_Alert));
  aon211d1 g2429__2398(.A (n_28), .B (n_15), .C1 (n_26), .C2 (n_31),
       .ZN (n_36));
  nr03d1 g2435__5107(.A1 (n_19), .A2 (n_11), .A3 (n_29), .ZN (n_35));
  ah01d1 g2433__6260(.A (n_20), .B (door_timer[2]), .CO (n_33), .S
       (n_34));
  oan211d1 g2432__4319(.A (n_24), .B (n_31), .C1 (n_13), .C2 (n_25),
       .ZN (n_32));
  oan211d1 g2434__8428(.A (n_64), .B (door_timer[7]), .C1 (n_8), .C2
       (door_timer[6]), .ZN (n_30));
  nd04d1 g2441__5526(.A1 (n_28), .A2 (n_14), .A3 (n_27), .A4 (n_31),
       .ZN (n_29));
  aor211d1 g2436__6783(.A (n_25), .B (n_24), .C1 (n_18), .C2
       (Out_Current_Floor[0]), .Z (n_26));
  an02d1 g2442__3680(.A1 (n_44), .A2 (n_22), .Z (n_23));
  nr03d1 g2439__1617(.A1 (Weight_Alert), .A2 (Door_Alert), .A3
       (Complete), .ZN (n_37));
  ah01d1 g2438__2802(.A (door_timer[1]), .B (door_timer[0]), .CO
       (n_20), .S (n_21));
  aoi22d1 g2443__1705(.A1 (n_18), .A2 (n_17), .B1 (Request_Floor[0]),
       .B2 (Out_Current_Floor[0]), .ZN (n_19));
  inv0d0 g2445(.I (n_28), .ZN (n_16));
  inv0d0 g2446(.I (n_15), .ZN (n_27));
  inv0d0 g2456(.I (n_24), .ZN (n_14));
  aoi22d1 g2437__5122(.A1 (Request_Floor[1]), .A2 (n_12), .B1
       (Request_Floor[0]), .B2 (n_17), .ZN (n_13));
  inv0d0 g2447(.I (n_22), .ZN (n_49));
  aoim22d1 g2444__8246(.A1 (Request_Floor[1]), .A2
       (Out_Current_Floor[1]), .B1 (Request_Floor[1]), .B2
       (Out_Current_Floor[1]), .Z (n_11));
  dfcrq1 Weight_Alert_reg(.CDN (n_74), .CP (clk), .D (Over_Weight), .Q
       (Weight_Alert));
  nd02d1 g2452__7098(.A1 (Request_Floor[3]), .A2 (n_10), .ZN (n_28));
  nd02d1 g2453__6131(.A1 (Request_Floor[2]), .A2 (n_9), .ZN (n_31));
  ora211d1 g2440__1881(.A (door_timer[4]), .B (door_timer[5]), .C1
       (door_timer[3]), .C2 (door_timer[2]), .Z (n_8));
  nr02d1 g2451__5115(.A1 (n_12), .A2 (Request_Floor[1]), .ZN (n_25));
  nr02d1 g2454__7482(.A1 (n_10), .A2 (Request_Floor[3]), .ZN (n_15));
  nr02d1 g2463__4733(.A1 (n_9), .A2 (Request_Floor[2]), .ZN (n_24));
  nd02d1 g2455__6161(.A1 (n_12), .A2 (n_17), .ZN (n_22));
  nd12d0 g2457__9315(.A1 (In_Current_Floor[1]), .A2 (reset), .ZN (n_7));
  nd02d0 g2448__9945(.A1 (In_Current_Floor[2]), .A2 (reset), .ZN (n_6));
  nd12d0 g2461__2883(.A1 (In_Current_Floor[3]), .A2 (reset), .ZN (n_5));
  nd12d0 g2458__2346(.A1 (In_Current_Floor[2]), .A2 (reset), .ZN (n_4));
  nd02d0 g2460__1666(.A1 (In_Current_Floor[0]), .A2 (reset), .ZN (n_3));
  nd02d0 g2459__7410(.A1 (In_Current_Floor[3]), .A2 (reset), .ZN (n_2));
  nd02d0 g2462__6417(.A1 (In_Current_Floor[1]), .A2 (reset), .ZN (n_1));
  nd12d0 g2449__5477(.A1 (In_Current_Floor[0]), .A2 (reset), .ZN (n_0));
  nd02d1 g2464__2398(.A1 (Out_Current_Floor[1]), .A2
       (Out_Current_Floor[0]), .ZN (n_44));
  inv0d0 g2470(.I (Out_Current_Floor[2]), .ZN (n_9));
  inv0d0 g2466(.I (Out_Current_Floor[1]), .ZN (n_12));
  inv0d0 g2471(.I (Out_Current_Floor[0]), .ZN (n_17));
  inv0d0 g2465(.I (Request_Floor[0]), .ZN (n_18));
  inv0d0 g2469(.I (Out_Current_Floor[3]), .ZN (n_10));
  inv0d0 g2467(.I (Door_Open), .ZN (n_64));
  inv0d0 g2468(.I (reset), .ZN (n_74));

pc3d01 IRequest_Floor0(.PAD(Request_Floor[0]),.CIN(Request_Floor[0]));
pc3d01 IRequest_Floor1(.PAD(Request_Floor[1]),.CIN(Request_Floor[1]));
pc3d01 IRequest_Floor2(.PAD(Request_Floor[2]),.CIN(Request_Floor[2]));
pc3d01 IRequest_Floor3(.PAD(Request_Floor[3]),.CIN(Request_Floor[3]));

pc3d01 IIn_Current_Floor0(.PAD(In_Current_Floor[0]),.CIN(In_Current_Floor[0]));
pc3d01 IIn_Current_Floor1(.PAD(In_Current_Floor[1]),.CIN(In_Current_Floor[1]));
pc3d01 IIn_Current_Floor2(.PAD(In_Current_Floor[2]),.CIN(In_Current_Floor[2]));
pc3d01 IIn_Current_Floor3(.PAD(In_Current_Floor[3]),.CIN(In_Current_Floor[3]));

pc3d01 IOver_Weight(.PAD(Over_Weight),.CIN(Over_Weight));
pc3d01 IDoor_Open(.PAD(Door_Open),.CIN(Door_Open));
pc3d01 IFloor_Sensor(.PAD(Floor_Sensor),.CIN(Floor_Sensor));
pc3d01 Iclk(.PAD(clk),.CIN(clk));
pc3d01 Ireset(.PAD(reset),.CIN(reset));


pc3d01 Out_Current_Floor0(.PAD(Out_Current_Floor[0]),.CIN(Out_Current_Floor[0]));
pc3d01 Out_Current_Floor1(.PAD(Out_Current_Floor[1]),.CIN(Out_Current_Floor[1]));
pc3d01 Out_Current_Floor2(.PAD(Out_Current_Floor[2]),.CIN(Out_Current_Floor[2]));
pc3d01 Out_Current_Floor3(.PAD(Out_Current_Floor[3]),.CIN(Out_Current_Floor[3]));


pc3d01 ODirection(.PAD(Direction),.CIN(Direction));
pc3d01 OComplete(.PAD(Complete),.CIN(Complete));
pc3d01 ODoor_Alert(.PAD(Door_Alert),.CIN(Door_Alert));
pc3d01 OWeight_Alert(.PAD(Weight_Alert),.CIN(Weight_Alert));


endmodule

